<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Start Learning_profile-image dialog-closed-mobile</name>
   <tag></tag>
   <elementGuidId>bf453f43-9689-462d-89b0-d5bca3f2dd6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/form/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.profile-image.dialog-closed-mobile</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7c457017-c9e0-45f8-a8b9-529b55fde2b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>profile-image dialog-closed-mobile</value>
      <webElementGuid>0afb191a-462c-4d4b-bbf1-da38677c0889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/avatar/2.svg</value>
      <webElementGuid>672e68f2-ffb9-4168-b0ec-bc2507638760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>User profile</value>
      <webElementGuid>60571aa2-5793-4faa-a278-70da7a4bfc47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;container-fluid ct-user-container&quot;]/div[@class=&quot;container ct-create-user&quot;]/form[1]/div[@class=&quot;row form&quot;]/div[@class=&quot;col-md-6 col-sm-12 row first-field-set&quot;]/div[@class=&quot;profile-image-container&quot;]/img[@class=&quot;profile-image dialog-closed-mobile&quot;]</value>
      <webElementGuid>c77cd4a7-3425-4db1-8127-f42e5423aa7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/form/div/div/div/img</value>
      <webElementGuid>a20a8452-6411-4012-ab95-735d4709a51e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='User profile']</value>
      <webElementGuid>ab822550-ce80-4cb9-8259-f36dd6994a23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>3cb319f8-7a1e-47d5-94d9-76b74e5cb446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/avatar/2.svg' and @alt = 'User profile']</value>
      <webElementGuid>976c3a90-ffa7-4560-a350-236e5138334f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
